DROP TABLE IF EXISTS quadra CASCADE;

CREATE TABLE quadra (
id SERIAL PRIMARY KEY,
nome VARCHAR(50) NOT NULL,
coberta BOOLEAN DEFAULT FALSE,
iluminacao BOOLEAN DEFAULT FALSE,
valor_hora NUMERIC(10, 2) NOT NULL,
ativa BOOLEAN DEFAULT TRUE
);
